// Curated editorial guide for Wrigleyville bars.
// Hand-picked with menu highlights, vibe tags, and game-day fit.
// Distance is approximate walking blocks from Wrigley Field's marquee gate.

export type BarVibe = 'party' | 'chill' | 'sports' | 'dive';
export type BarGroupFit = 'solo' | 'small' | 'large';
export type BarGameTiming = 'pregame' | 'ingame' | 'postgame';

export interface CuratedBar {
  id: string;
  name: string;
  slug: string;
  address: string;
  blocksFromWrigley: number; // 0 = on the corner, 5 = ~5 blocks
  tagline: string; // pull-quote, editorial
  whyFansLoveIt: string; // 1-2 sentence editorial
  vibe: BarVibe[];
  groupFit: BarGroupFit[];
  bestFor: BarGameTiming[];
  signature: { drink: string; price: string }; // signature drink
  menuHighlights: string[]; // 3-4 menu items
  food: 'full-kitchen' | 'bar-snacks' | 'no-food';
  specials: string; // current/typical special (editorial, not partner-confirmed)
  hours: string;
  capacity: 'intimate' | 'medium' | 'big-house';
  outdoor: boolean;
  rooftop: boolean;
  cashOnly: boolean;
  established: number;
  emoji: string; // single character signature
  accent: string; // tailwind hue family for accent stripe
}

export const CURATED_BARS: CuratedBar[] = [
  {
    id: 'murphys-bleachers',
    name: "Murphy's Bleachers",
    slug: 'murphys-bleachers',
    address: '3655 N Sheffield Ave',
    blocksFromWrigley: 0,
    tagline: 'The unofficial 8th-inning living room of the bleacher faithful.',
    whyFansLoveIt:
      "Sheffield-side institution since '80. Walk out, walk into the bleacher gate. The patio after a win sounds like a third-deck roar.",
    vibe: ['party', 'sports'],
    groupFit: ['small', 'large'],
    bestFor: ['pregame', 'postgame'],
    signature: { drink: 'Old Style draft', price: '$6' },
    menuHighlights: ['Italian Beef', 'Murphy Burger', 'Soft pretzel', 'Cubs Cheesesteak'],
    food: 'full-kitchen',
    specials: 'Win-day shot specials · $5 Old Style after wins',
    hours: '11a–2a (game days open earlier)',
    capacity: 'big-house',
    outdoor: true,
    rooftop: false,
    cashOnly: false,
    established: 1980,
    emoji: '',
    accent: 'cubs-blue',
  },
  {
    id: 'cubby-bear',
    name: 'The Cubby Bear',
    slug: 'cubby-bear',
    address: '1059 W Addison St',
    blocksFromWrigley: 0,
    tagline: 'Across the street from the marquee. Under the lights since 1953.',
    whyFansLoveIt:
      'The legendary corner spot. Live music nights, bigger-than-life crowds, and a stage that has hosted everyone from Steve Goodman to Pearl Jam.',
    vibe: ['party', 'sports'],
    groupFit: ['large'],
    bestFor: ['pregame', 'postgame'],
    signature: { drink: 'Cubby Mule', price: '$11' },
    menuHighlights: ['Buffalo wings', 'Loaded nachos', 'BBQ pork sandwich'],
    food: 'full-kitchen',
    specials: 'Live music post-game · $4 domestic drafts pregame',
    hours: '11a–2a · 3a Sat',
    capacity: 'big-house',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1953,
    emoji: '',
    accent: 'red',
  },
  {
    id: 'sluggers',
    name: 'Sluggers World Class Sports Bar',
    slug: 'sluggers',
    address: '3540 N Clark St',
    blocksFromWrigley: 1,
    tagline: 'Two stories, batting cages, and a dance floor. The 9th-inning detour.',
    whyFansLoveIt:
      'The upstairs is the loudest postgame floor on Clark. Batting cages, Pop-A-Shot, dueling pianos some nights — it is a choose-your-own-adventure.',
    vibe: ['party', 'sports'],
    groupFit: ['large'],
    bestFor: ['postgame'],
    signature: { drink: 'Bucket of 5 Old Style', price: '$25' },
    menuHighlights: ['Wings', 'Personal pizza', 'Loaded fries'],
    food: 'bar-snacks',
    specials: 'Bucket-of-5 deals · Postgame dance floor opens at 9p',
    hours: '11a–2a · 3a Sat',
    capacity: 'big-house',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1985,
    emoji: '',
    accent: 'amber',
  },
  {
    id: 'bernies',
    name: "Bernie's Bar & Grill",
    slug: 'bernies',
    address: '3664 N Clark St',
    blocksFromWrigley: 1,
    tagline: 'A neighborhood corner bar that just happens to be next to Wrigley.',
    whyFansLoveIt:
      'Family-run since the 70s. Wood floors, real bartenders, no nonsense. The kind of place a regular still has a stool waiting.',
    vibe: ['chill', 'dive'],
    groupFit: ['solo', 'small'],
    bestFor: ['pregame', 'ingame', 'postgame'],
    signature: { drink: 'Old Style + Malört shot', price: '$8' },
    menuHighlights: ['Italian Beef', 'Polish sausage', 'Burger'],
    food: 'full-kitchen',
    specials: 'Shot-and-a-beer combos · Cash-friendly happy hour',
    hours: '10a–2a',
    capacity: 'medium',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1972,
    emoji: '',
    accent: 'cubs-blue',
  },
  {
    id: 'merkles',
    name: "Merkle's Bar & Grill",
    slug: 'merkles',
    address: '3516 N Clark St',
    blocksFromWrigley: 2,
    tagline: 'Brunch before first pitch. Bourbon after the last out.',
    whyFansLoveIt:
      'Two-story, big patio, full menu. The morning brunch crowd flips into the postgame whiskey crowd without missing a beat.',
    vibe: ['party', 'sports'],
    groupFit: ['small', 'large'],
    bestFor: ['pregame', 'postgame'],
    signature: { drink: 'Bourbon flight', price: '$18' },
    menuHighlights: ['Pretzel pull-apart', 'Burger', 'Brunch hash', 'Wings'],
    food: 'full-kitchen',
    specials: 'Brunch til 3p · Bourbon happy hour M–Th',
    hours: '10a–2a',
    capacity: 'big-house',
    outdoor: true,
    rooftop: false,
    cashOnly: false,
    established: 2014,
    emoji: '',
    accent: 'amber',
  },
  {
    id: 'mordecai',
    name: 'Mordecai',
    slug: 'mordecai',
    address: '3632 N Clark St',
    blocksFromWrigley: 1,
    tagline: 'Speakeasy whiskey bar named for Three-Finger Brown. Date-night calibre.',
    whyFansLoveIt:
      'The grown-up Wrigleyville move. 200+ whiskeys, leather booths, real cocktails. Bring someone you want to impress.',
    vibe: ['chill'],
    groupFit: ['solo', 'small'],
    bestFor: ['pregame', 'postgame'],
    signature: { drink: 'Three-Finger Old Fashioned', price: '$16' },
    menuHighlights: ['Hot chicken sandwich', 'Pork belly bao', 'Cheese board'],
    food: 'full-kitchen',
    specials: 'Reverse happy hour 10p–close · whiskey flights',
    hours: '4p–2a',
    capacity: 'intimate',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 2016,
    emoji: '',
    accent: 'red',
  },
  {
    id: 'old-crow',
    name: 'Old Crow Smokehouse',
    slug: 'old-crow',
    address: '3506 N Clark St',
    blocksFromWrigley: 2,
    tagline: 'BBQ, bourbon, and a rooftop with a view of the Friendly Confines.',
    whyFansLoveIt:
      'Country-bar energy with serious brisket. The rooftop is one of the few places you can sip a Manhattan and watch the L roll past Wrigley.',
    vibe: ['party'],
    groupFit: ['small', 'large'],
    bestFor: ['postgame'],
    signature: { drink: 'Whiskey peach lemonade', price: '$13' },
    menuHighlights: ['Brisket', 'Pulled pork', 'Mac & cheese', 'Cornbread'],
    food: 'full-kitchen',
    specials: 'Rooftop reservations recommended · Sunday rib night',
    hours: '11a–2a',
    capacity: 'big-house',
    outdoor: true,
    rooftop: true,
    cashOnly: false,
    established: 2014,
    emoji: '',
    accent: 'amber',
  },
  {
    id: 'lucky-dorr',
    name: 'Lucky Dorr',
    slug: 'lucky-dorr',
    address: '1101 W Waveland Ave',
    blocksFromWrigley: 0,
    tagline: 'Cubs-owned beer hall on Gallagher Way. Family-friendly, fast pours.',
    whyFansLoveIt:
      'Operated by the Ricketts family right outside the park. Big pretzels, local drafts, and easy access to the plaza concerts.',
    vibe: ['chill', 'sports'],
    groupFit: ['small', 'large'],
    bestFor: ['pregame'],
    signature: { drink: 'Half Acre Daisy Cutter', price: '$9' },
    menuHighlights: ['Bavarian pretzel', 'Smashburger', 'Chicken sandwich'],
    food: 'full-kitchen',
    specials: 'Pre-game sampler flights · Plaza concert nights',
    hours: '11a–11p (game days)',
    capacity: 'medium',
    outdoor: true,
    rooftop: false,
    cashOnly: false,
    established: 2019,
    emoji: '',
    accent: 'cubs-blue',
  },
  {
    id: 'vines',
    name: 'Vines on Clark',
    slug: 'vines',
    address: '3554 N Clark St',
    blocksFromWrigley: 1,
    tagline: 'Frozen drinks, palm trees, and the loudest patio on Clark.',
    whyFansLoveIt:
      'Tiki escape in the middle of Wrigleyville. Frozen rosé, bushwackers, and a patio that turns into a block party after a win.',
    vibe: ['party'],
    groupFit: ['large'],
    bestFor: ['postgame'],
    signature: { drink: 'Frozen bushwacker', price: '$12' },
    menuHighlights: ['Truffle fries', 'Tacos', 'Chicken bites'],
    food: 'bar-snacks',
    specials: 'Frozen drink BOGO · DJ nights Fri–Sat',
    hours: '11a–2a · 3a Sat',
    capacity: 'big-house',
    outdoor: true,
    rooftop: false,
    cashOnly: false,
    established: 2007,
    emoji: '',
    accent: 'red',
  },
  {
    id: 'gman',
    name: 'GMan Tavern',
    slug: 'gman',
    address: '3740 N Clark St',
    blocksFromWrigley: 1,
    tagline: "The thinking fan's dive. Live bands, board games, no TVs front of house.",
    whyFansLoveIt:
      'Sister bar to Metro upstairs. Punk-rock pedigree, killer jukebox, and the rare Wrigleyville bar that feels like the rest of Chicago.',
    vibe: ['dive', 'chill'],
    groupFit: ['solo', 'small'],
    bestFor: ['pregame', 'postgame'],
    signature: { drink: 'Daisy Cutter on draft', price: '$7' },
    menuHighlights: ['Pretzel knots', 'Pizza by the slice'],
    food: 'bar-snacks',
    specials: 'Live bands W–Sat · $3 PBR all day',
    hours: '4p–2a',
    capacity: 'medium',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 2007,
    emoji: '',
    accent: 'red',
  },
  {
    id: 'yak-zies',
    name: "Yak-Zie's Bar & Grill",
    slug: 'yak-zies',
    address: '3710 N Clark St',
    blocksFromWrigley: 1,
    tagline: "A Cubs-fan dive with a paint-peeling history and a cult Italian beef.",
    whyFansLoveIt:
      "If you know, you know. Unpretentious, cash-friendly, and the beef sandwich is whispered about in every group chat after a 7-1 win.",
    vibe: ['dive', 'sports'],
    groupFit: ['solo', 'small'],
    bestFor: ['pregame', 'ingame', 'postgame'],
    signature: { drink: 'Pitcher of Old Style', price: '$14' },
    menuHighlights: ['Italian beef', 'Wings', 'Cheeseburger'],
    food: 'full-kitchen',
    specials: 'Pitcher specials all game · cash discount',
    hours: '11a–2a',
    capacity: 'medium',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1971,
    emoji: '',
    accent: 'cubs-blue',
  },
  {
    id: 'sports-corner',
    name: 'The Sports Corner',
    slug: 'sports-corner',
    address: '956 W Addison St',
    blocksFromWrigley: 0,
    tagline: 'Pure sports-bar DNA. 30+ TVs. Every angle of every play.',
    whyFansLoveIt:
      "Across from the firehouse. The bar where you go when you actually want to *watch* the game and don't trust the crowd to settle down.",
    vibe: ['sports'],
    groupFit: ['small', 'large'],
    bestFor: ['ingame'],
    signature: { drink: 'Bloody Mary', price: '$10' },
    menuHighlights: ['Wings', 'Burger', 'Quesadilla', 'Wings'],
    food: 'full-kitchen',
    specials: 'NFL Sunday ticket · $5 Bloodys before 1p',
    hours: '11a–2a',
    capacity: 'big-house',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1995,
    emoji: '',
    accent: 'amber',
  },
  {
    id: 'dugout',
    name: 'The Dugout',
    slug: 'dugout',
    address: '950 W Addison St',
    blocksFromWrigley: 0,
    tagline: 'Underground dive a literal long-toss from home plate.',
    whyFansLoveIt:
      'Down the stairs into a windowless cave. Locals, ushers, and a few Cubs employees end up here. Cheap pours, zero pretense.',
    vibe: ['dive'],
    groupFit: ['solo', 'small'],
    bestFor: ['postgame'],
    signature: { drink: 'Whiskey shot + High Life', price: '$7' },
    menuHighlights: ['Frozen pizza', 'Popcorn'],
    food: 'bar-snacks',
    specials: 'Cash specials · usher discount (just ask)',
    hours: '4p–2a',
    capacity: 'intimate',
    outdoor: false,
    rooftop: false,
    cashOnly: false,
    established: 1968,
    emoji: '',
    accent: 'cubs-blue',
  },
  {
    id: 'stretch',
    name: 'Stretch Bar & Grill',
    slug: 'stretch',
    address: '3485 N Clark St',
    blocksFromWrigley: 2,
    tagline: 'Two patios, brunch all day, and the most efficient kitchen on Clark.',
    whyFansLoveIt:
      'Big group? Walk in 30 deep, get sat in 15 minutes. Reliable food, big TVs, and a back patio that absorbs the postgame surge.',
    vibe: ['sports', 'party'],
    groupFit: ['small', 'large'],
    bestFor: ['pregame', 'ingame'],
    signature: { drink: 'Big-batch margarita pitcher', price: '$36' },
    menuHighlights: ['Brunch tacos', 'Buffalo chicken sandwich', 'Wings'],
    food: 'full-kitchen',
    specials: 'All-day brunch · pitcher deals during games',
    hours: '10a–2a',
    capacity: 'big-house',
    outdoor: true,
    rooftop: false,
    cashOnly: false,
    established: 2010,
    emoji: '',
    accent: 'amber',
  },
];

export const VIBE_LABELS: Record<BarVibe, { label: string; emoji: string }> = {
  party: { label: 'Party', emoji: '' },
  chill: { label: 'Chill', emoji: '' },
  sports: { label: 'Sports', emoji: '' },
  dive: { label: 'Dive', emoji: '' },
};

export const GROUP_LABELS: Record<BarGroupFit, { label: string; emoji: string }> = {
  solo: { label: 'Solo / Duo', emoji: '' },
  small: { label: 'Small (3-5)', emoji: '' },
  large: { label: 'Crew (6+)', emoji: '' },
};

export const TIMING_LABELS: Record<BarGameTiming, { label: string; emoji: string }> = {
  pregame: { label: 'Pre-game', emoji: '' },
  ingame: { label: 'In-game', emoji: '' },
  postgame: { label: 'Post-game', emoji: '' },
};

export const DISTANCE_BUCKETS = [
  { key: 'walking', label: '≤ 2 blocks', max: 2 },
  { key: 'close', label: '≤ 4 blocks', max: 4 },
  { key: 'all', label: 'All', max: 99 },
] as const;
export type DistanceBucket = (typeof DISTANCE_BUCKETS)[number]['key'];
