project_id = "saqtmgjbuwimvxtrauvb"

[functions.meetup-suggestions]
verify_jwt = false

[functions.post-game]
verify_jwt = false

[functions.smart-notifications]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.gameday-push]
verify_jwt = false
