import { useEffect } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

export interface BeerShoutoutRow {
  id: string;
  tip_id: string;
  sender_id: string;
  recipient_id: string;
  credits: number;
  message: string | null;
  is_auto_generated: boolean;
  created_at: string;
  expires_at: string;
}

export interface ShoutoutProfile {
  user_id: string;
  display_name: string;
  profile_photo: string | null;
}

export interface BeerShoutoutWithProfiles extends BeerShoutoutRow {
  sender: ShoutoutProfile | null;
  recipient: ShoutoutProfile | null;
}

/**
 * Live feed of beer shoutouts (last 24h, auto-generated by send_beer_tip RPC).
 * Subscribes to realtime so new shoutouts appear within ~1s.
 */
export function useBeerShoutouts(limit = 25) {
  const qc = useQueryClient();

  const query = useQuery({
    queryKey: ['beer-shoutouts', limit],
    queryFn: async (): Promise<BeerShoutoutWithProfiles[]> => {
      const { data: rows, error } = await supabase
        .from('beer_shoutouts')
        .select('*')
        .gt('expires_at', new Date().toISOString())
        .order('created_at', { ascending: false })
        .limit(limit);
      if (error) throw error;
      const shoutouts = (rows ?? []) as BeerShoutoutRow[];
      if (shoutouts.length === 0) return [];

      const userIds = Array.from(
        new Set(shoutouts.flatMap((s) => [s.sender_id, s.recipient_id])),
      );
      const { data: profiles } = await supabase.rpc('get_public_profiles', {
        p_user_ids: userIds,
      });
      const profMap: Record<string, ShoutoutProfile> = {};
      (profiles ?? []).forEach((p: any) => {
        profMap[p.user_id] = {
          user_id: p.user_id,
          display_name: p.display_name ?? 'A fan',
          profile_photo: p.profile_photo ?? null,
        };
      });

      return shoutouts.map((s) => ({
        ...s,
        sender: profMap[s.sender_id] ?? null,
        recipient: profMap[s.recipient_id] ?? null,
      }));
    },
    refetchInterval: 60_000,
    staleTime: 30_000,
  });

  // Realtime: invalidate the cache when a new shoutout lands.
  useEffect(() => {
    const channel = supabase
      .channel('beer-shoutouts-feed')
      .on(
        'postgres_changes',
        { event: 'INSERT', schema: 'public', table: 'beer_shoutouts' },
        () => qc.invalidateQueries({ queryKey: ['beer-shoutouts'] }),
      )
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
  }, [qc]);

  return query;
}

/* ───── Buyer count + badge tier ───── */

export type BuyerBadgeTier = 'legend' | 'regular' | 'first' | null;

export interface BuyerBadge {
  tier: BuyerBadgeTier;
  label: string;
  emoji: string;
  count: number;
}

function badgeFromCount(count: number): BuyerBadge {
  if (count >= 20) {
    return { tier: 'legend', label: 'Legend of the Bleachers', emoji: '🏆', count };
  }
  if (count >= 5) {
    return { tier: 'regular', label: 'Round Regular', emoji: '🍺', count };
  }
  if (count >= 1) {
    return { tier: 'first', label: 'First Round', emoji: '🍺', count };
  }
  return { tier: null, label: '', emoji: '', count: 0 };
}

/**
 * Buyer badge for any user (own card, profile header, shoutout chip).
 * Realtime: subscribes to beer_tips for this sender so the badge updates live.
 */
export function useBeerBuyerBadge(userId: string | null | undefined) {
  const qc = useQueryClient();
  const { user } = useAuth();

  const query = useQuery({
    queryKey: ['beer-buyer-count', userId],
    enabled: !!userId,
    queryFn: async (): Promise<BuyerBadge> => {
      const { data, error } = await supabase.rpc('get_beer_buyer_count', {
        p_user_id: userId!,
      });
      if (error) throw error;
      return badgeFromCount((data as number) ?? 0);
    },
    staleTime: 30_000,
  });

  useEffect(() => {
    if (!userId) return;
    // Only subscribe live for the viewing user (RLS would silently drop others' rows
    // anyway for beer_tips changes that aren't ours). The query also auto-refetches
    // every 30s for other profiles.
    if (user?.id !== userId) return;
    const channel = supabase
      .channel(`beer-tips-sender-${userId}`)
      .on(
        'postgres_changes',
        {
          event: 'INSERT',
          schema: 'public',
          table: 'beer_tips',
          filter: `sender_id=eq.${userId}`,
        },
        () => qc.invalidateQueries({ queryKey: ['beer-buyer-count', userId] }),
      )
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
  }, [userId, user?.id, qc]);

  return query;
}
